name: "Bypass branch protection"
description: "Bypasses branch protection rules"
inputs:
  backup:
    description: "The branch generated protection backup JSON"
    required: false
  branch:
    description: "The branch to target"
    required: true
    default: main
  token:
    description: "GitHub user token with administrative privileges"
    required: true
  repository:
    description: "The repository to target (<Owner>/<Repository>)"
    required: true
    default: ${{github.repository}}
outputs:
  backup:
    description: "The branch generated protection backup JSON"
runs:
  using: "node12"
  main: "dist/index.js"
